version: "3.7"

networks:
  default:
    external: true
    name: aline

services:
  bank-service:
    build: .
    image: aline/underwriter-microservice
    env_file:
      - .env
    ports:
      - 8071:${APP_PORT}
